services:
  - type: web
    name: school-management-system
    env: python
    plan: free
    buildCommand: |
      pip install -r requirements.txt
      python manage.py collectstatic --noinput
      python manage.py migrate --noinput
    startCommand: |
      gunicorn Analitica.wsgi:application --workers=3 --timeout=120 --log-file -
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.4
      - key: DJANGO_SETTINGS_MODULE
        value: Analitica.settings
      - key: DJANGO_DEBUG
        value: "false"
      - key: DJANGO_ALLOWED_HOSTS
        value: .onrender.com,localhost
      # Set these in the Render dashboard after first deploy (do not commit secrets)
      - key: DJANGO_SECRET_KEY
        sync: false
      - key: RESEND_API_KEY
        sync: false
      - key: EMAIL_HOST_USER
        sync: false
      - key: EMAIL_HOST_PASSWORD
        sync: false
      - key: MPESA_CONSUMER_KEY
        sync: false
      - key: MPESA_CONSUMER_SECRET
        sync: false
      - key: MPESA_CALLBACK_URL
        sync: false
    disk:
      name: media
      mountPath: /opt/render/project/src/media
      sizeGB: 1
    autoDeploy: true

databases:
  - name: sms-postgres
    plan: free
    databaseName: sms
    user: sms
    ipAllowList: []
