# Generated by Django 5.2.3 on 2025-06-26 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_event'),
        ('core', '0008_term_end_date_term_start_date'),
    ]

    operations = [
    ]
