# Generated by Django 5.2.3 on 2025-06-26 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_merge_0006_event_0008_term_end_date_term_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='type',
            field=models.CharField(choices=[('opener', 'Opener exams'), ('midterm', 'Mid-term exams'), ('endterm', 'End-Term exams'), ('others', 'Others')], default='others', max_length=10),
        ),
    ]
