# Generated by Django 5.2.3 on 2025-06-26 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_exam_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='level',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
