# Generated by Django 5.2.3 on 2025-06-30 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_event_category_event_term'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='classes',
            field=models.ManyToManyField(related_name='exams', to='core.class'),
        ),
        migrations.AddField(
            model_name='exam',
            name='subjects',
            field=models.ManyToManyField(related_name='exams', to='core.subject'),
        ),
    ]
