# Generated by Django 5.2.3 on 2025-07-01 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_exam_classes_exam_subjects'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exam',
            name='classes',
        ),
        migrations.RemoveField(
            model_name='exam',
            name='subjects',
        ),
    ]
