# Generated by Django 5.2.3 on 2025-07-02 07:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_fee_studentfeeassignment'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeeCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='studentfeeassignment',
            name='fee',
        ),
        migrations.RemoveField(
            model_name='studentfeeassignment',
            name='student',
        ),
        migrations.CreateModel(
            name='FeeAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('class_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fee_assignments', to='core.class')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fee_assignments', to='core.term')),
                ('fee_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='core.feecategory')),
            ],
            options={
                'unique_together': {('fee_category', 'class_group', 'term')},
            },
        ),
        migrations.CreateModel(
            name='FeePayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_date', models.DateTimeField(auto_now_add=True)),
                ('payment_method', models.CharField(blank=True, max_length=50, null=True)),
                ('reference', models.CharField(blank=True, max_length=100, null=True)),
                ('fee_assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='core.feeassignment')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fee_payments', to='core.student')),
            ],
            options={
                'ordering': ['-payment_date'],
            },
        ),
        migrations.DeleteModel(
            name='Fee',
        ),
        migrations.DeleteModel(
            name='StudentFeeAssignment',
        ),
    ]
