# Generated by Django 5.2.3 on 2025-07-14 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_student_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='postal_address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
