# Generated by Django 5.2.3 on 2025-07-22 05:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_message'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={},
        ),
    ]
