# Generated by Django 5.2.2 on 2025-07-28 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_timetablelog_timetableslot'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='color',
            field=models.CharField(default='#007bff', help_text='Color for the timetable events', max_length=7),
        ),
    ]
