# Generated by Django 5.2.2 on 2025-07-28 14:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_notification'),
    ]

    operations = [
        migrations.CreateModel(
            name='PeriodSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('label', models.CharField(help_text='e.g., "Period 1", "Break"', max_length=50)),
                ('is_class_slot', models.BooleanField(default=True, help_text='Is this a slot for a class or a break?')),
            ],
            options={
                'ordering': ['start_time'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='timetableslot',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='timetableslot',
            name='class_group',
        ),
        migrations.RemoveField(
            model_name='timetableslot',
            name='subject',
        ),
        migrations.RemoveField(
            model_name='timetableslot',
            name='teacher',
        ),
        migrations.RemoveField(
            model_name='timetableslot',
            name='term',
        ),
        migrations.CreateModel(
            name='DefaultTimetable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday')], max_length=10)),
                ('editable', models.BooleanField(default=True)),
                ('class_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timetable_entries', to='core.class')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.subject')),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.teacher')),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.periodslot')),
            ],
            options={
                'ordering': ['class_group', 'day', 'period__start_time'],
                'unique_together': {('class_group', 'day', 'period')},
            },
        ),
        migrations.DeleteModel(
            name='TimeTableLog',
        ),
        migrations.DeleteModel(
            name='TimeTableSlot',
        ),
    ]
