# Generated by Django 5.2.2 on 2025-07-28 14:14

from django.db import migrations
import datetime

PERIOD_SLOTS_DATA = [
    {"start_time": datetime.time(8, 0), "end_time": datetime.time(8, 40), "label": "Period 1", "is_class_slot": True},
    {"start_time": datetime.time(8, 40), "end_time": datetime.time(9, 20), "label": "Period 2", "is_class_slot": True},
    {"start_time": datetime.time(9, 20), "end_time": datetime.time(9, 40), "label": "Break", "is_class_slot": False},
    {"start_time": datetime.time(9, 40), "end_time": datetime.time(10, 20), "label": "Period 3", "is_class_slot": True},
    {"start_time": datetime.time(10, 20), "end_time": datetime.time(11, 0), "label": "Period 4", "is_class_slot": True},
    {"start_time": datetime.time(11, 0), "end_time": datetime.time(11, 40), "label": "Lunch", "is_class_slot": False},
    {"start_time": datetime.time(11, 40), "end_time": datetime.time(12, 20), "label": "Period 5", "is_class_slot": True},
    {"start_time": datetime.time(12, 20), "end_time": datetime.time(13, 0), "label": "Period 6", "is_class_slot": True},
    {"start_time": datetime.time(13, 0), "end_time": datetime.time(13, 40), "label": "Period 7", "is_class_slot": True},
    {"start_time": datetime.time(13, 40), "end_time": datetime.time(14, 20), "label": "Period 8", "is_class_slot": True},
]

def populate_period_slots(apps, schema_editor):
    PeriodSlot = apps.get_model('core', 'PeriodSlot')
    for slot_data in PERIOD_SLOTS_DATA:
        PeriodSlot.objects.create(**slot_data)

def clear_period_slots(apps, schema_editor):
    PeriodSlot = apps.get_model('core', 'PeriodSlot')
    PeriodSlot.objects.all().delete()

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_periodslot_alter_timetableslot_unique_together_and_more'),
    ]

    operations = [
        migrations.RunPython(populate_period_slots, reverse_code=clear_period_slots),
    ]
