# Generated by Django 5.2.4 on 2025-07-31 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_remove_message_recipients_message_recipient_and_more'),
        ('core', '0028_populate_period_slots'),
    ]

    operations = [
    ]
