# Generated by Django 5.2.2 on 2025-08-04 17:49

from django.db import migrations

def populate_exam_dates(apps, schema_editor):
    Exam = apps.get_model('core', 'Exam')
    # We only need to populate exams where start_date is null
    for exam in Exam.objects.filter(start_date__isnull=True).select_related('term'):
        # Use the term's start_date as a sensible default
        if exam.term and exam.term.start_date:
            exam.start_date = exam.term.start_date
            exam.end_date = exam.term.start_date # Set end_date to the same as start_date
            exam.save()

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_remove_exam_date_exam_end_date_exam_start_date_and_more'),
    ]

    operations = [
        migrations.RunPython(populate_exam_dates, reverse_code=migrations.RunPython.noop),
    ]
