# Generated by Django 5.2.3 on 2025-08-04 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_teacherresponsibility'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherresponsibility',
            name='end_date',
            field=models.DateField(blank=True, help_text='End date of the responsibility assignment', null=True),
        ),
        migrations.AddField(
            model_name='teacherresponsibility',
            name='start_date',
            field=models.DateField(blank=True, help_text='Start date of the responsibility assignment', null=True),
        ),
    ]
