# Generated by Django 5.2.3 on 2025-08-06 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_teacherresponsibility_end_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='feepayment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Verification'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10),
        ),
    ]
