# Generated by Django 5.2.3 on 2025-08-06 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_feepayment_status'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='feepayment',
            constraint=models.UniqueConstraint(fields=('reference',), name='unique_mpesa_reference'),
        ),
    ]
