# Generated by Django 5.2.3 on 2025-08-07 18:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_broadcastmessage_message_broadcast_group_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feepayment',
            name='fee_assignment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='core.feeassignment'),
        ),
    ]
