# Generated by Django 5.2.3 on 2025-08-07 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_alter_feepayment_fee_assignment'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='extra_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
