# Generated by Django 5.2.3 on 2025-08-08 05:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_populate_exam_dates'),
        ('core', '0037_message_extra_id'),
    ]

    operations = [
    ]
