# Generated by Django 5.2.3 on 2025-08-11 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_merge_0031_populate_exam_dates_0037_message_extra_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='extra_id',
        ),
        migrations.AlterField(
            model_name='exam',
            name='end_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='exam',
            name='start_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
