# Generated by Django 5.2.4 on 2025-08-14 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0041_alter_attendance_unique_together_attendance_period_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='weekly_lessons',
            field=models.PositiveIntegerField(default=3, help_text='Average lessons per week (default 3)'),
        ),
    ]
