# Generated by Django 5.2.3 on 2025-08-14 18:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0043_mpesatransaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='feepayment',
            name='mpesa_transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='core.mpesatransaction'),
        ),
    ]
