# Generated by Django 5.2.3 on 2025-08-16 18:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0045_alter_user_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubjectComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.FloatField(default=1.0, help_text='Optional weight multiplier for this child when aggregating to parent')),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='part_of', to='core.subject')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_components', to='core.subject')),
            ],
            options={
                'verbose_name': 'Subject Component',
                'verbose_name_plural': 'Subject Components',
                'unique_together': {('parent', 'child')},
            },
        ),
    ]
