# Generated by Django 5.2.3 on 2025-08-16 21:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0046_subjectcomponent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='class_teacher',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.teacher'),
        ),
    ]
