# Generated by Django 5.0.7 on 2025-08-20 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0048_exam_published_at_exam_results_published_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MpesaC2BLedger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trans_id', models.CharField(db_index=True, max_length=30, unique=True)),
                ('trans_time', models.CharField(blank=True, max_length=20, null=True)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('msisdn', models.CharField(blank=True, max_length=20, null=True)),
                ('bill_ref', models.CharField(blank=True, max_length=100, null=True)),
                ('business_short_code', models.CharField(blank=True, max_length=20, null=True)),
                ('third_party_trans_id', models.CharField(blank=True, max_length=64, null=True)),
                ('first_name', models.CharField(blank=True, max_length=100, null=True)),
                ('middle_name', models.CharField(blank=True, max_length=100, null=True)),
                ('last_name', models.CharField(blank=True, max_length=100, null=True)),
                ('org_account_balance', models.CharField(blank=True, max_length=100, null=True)),
                ('raw', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
