# Generated by Django 5.2.4 on 2025-08-24 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0049_mpesac2bledger'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='min_weekly_lessons',
            field=models.PositiveIntegerField(default=3, help_text='Minimum lessons per week to enforce in the timetable (default 3)'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='weekly_lessons',
            field=models.PositiveIntegerField(default=3, help_text='Average/target lessons per week (default 3)'),
        ),
        migrations.AddIndex(
            model_name='feeassignment',
            index=models.Index(fields=['class_group', 'term'], name='core_feeass_class_g_5518d6_idx'),
        ),
        migrations.AddIndex(
            model_name='feeassignment',
            index=models.Index(fields=['term'], name='core_feeass_term_id_eb93fe_idx'),
        ),
        migrations.AddIndex(
            model_name='feepayment',
            index=models.Index(fields=['student'], name='core_feepay_student_f6d8f8_idx'),
        ),
        migrations.AddIndex(
            model_name='feepayment',
            index=models.Index(fields=['fee_assignment'], name='core_feepay_fee_ass_346c54_idx'),
        ),
        migrations.AddIndex(
            model_name='feepayment',
            index=models.Index(fields=['payment_date'], name='core_feepay_payment_7504a3_idx'),
        ),
        migrations.AddIndex(
            model_name='feepayment',
            index=models.Index(fields=['status'], name='core_feepay_status_71226d_idx'),
        ),
        migrations.AddIndex(
            model_name='grade',
            index=models.Index(fields=['student', 'exam'], name='core_grade_student_93f886_idx'),
        ),
        migrations.AddIndex(
            model_name='grade',
            index=models.Index(fields=['exam'], name='core_grade_exam_id_aaee36_idx'),
        ),
        migrations.AddIndex(
            model_name='grade',
            index=models.Index(fields=['subject'], name='core_grade_subject_585419_idx'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['class_group'], name='core_studen_class_g_47135b_idx'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['phone'], name='core_studen_phone_d6a640_idx'),
        ),
    ]
