# Generated by Django 5.2.4 on 2025-08-25 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0050_subject_min_weekly_lessons_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_type', models.CharField(choices=[('exam_publish', 'Exam Publish Notifications'), ('fee_arrears', 'Fee Arrears Notifications')], max_length=30)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('done', 'Done'), ('failed', 'Failed')], default='queued', max_length=10)),
                ('total', models.PositiveIntegerField(default=0)),
                ('processed', models.PositiveIntegerField(default=0)),
                ('success_count', models.PositiveIntegerField(default=0)),
                ('error_count', models.PositiveIntegerField(default=0)),
                ('meta', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['job_type'], name='core_notifi_job_typ_253b61_idx'), models.Index(fields=['status'], name='core_notifi_status_ee6e9c_idx'), models.Index(fields=['created_at'], name='core_notifi_created_bcf130_idx')],
            },
        ),
    ]
