# Generated by Django 5.2.4 on 2025-08-25 21:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0051_notificationjob'),
    ]

    operations = [
        migrations.CreateModel(
            name='GradeCommentTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade_letter', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E'), ('F', 'F')], max_length=2, unique=True)),
                ('comment', models.TextField(help_text='Comment shown in gradebooks for this grade letter')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Grade Comment Template',
                'verbose_name_plural': 'Grade Comment Templates',
            },
        ),
    ]
