# Generated by Django 5.0.7 on 2025-08-27 11:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0053_resultblock'),
    ]

    operations = [
        migrations.CreateModel(
            name='PocketMoney',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('deposit', 'Deposit'), ('withdrawal', 'Withdrawal'), ('adjustment', 'Adjustment')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField(blank=True, help_text='Optional description for the transaction', null=True)),
                ('transaction_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='approved', max_length=10)),
                ('reference', models.CharField(blank=True, help_text='Reference number or receipt', max_length=100, null=True)),
                ('processed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_pocket_money', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pocket_money_transactions', to='core.student')),
            ],
            options={
                'ordering': ['-transaction_date'],
                'indexes': [models.Index(fields=['student'], name='core_pocket_student_f7c7c5_idx'), models.Index(fields=['transaction_date'], name='core_pocket_transac_ecea9c_idx'), models.Index(fields=['transaction_type'], name='core_pocket_transac_d08984_idx'), models.Index(fields=['status'], name='core_pocket_status_d50ed4_idx')],
            },
        ),
    ]
