# Generated by Django 5.2.4 on 2025-09-01 10:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0054_pocketmoney'),
    ]

    operations = [
        migrations.CreateModel(
            name='OptionalChargeCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='feepayment',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fee_payments', to='core.student'),
        ),
        migrations.CreateModel(
            name='OptionalOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='core.optionalchargecategory')),
                ('class_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='optional_offers', to='core.class')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='optional_offers', to='core.term')),
            ],
        ),
        migrations.CreateModel(
            name='StudentOptionalCharge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('cancelled', 'Cancelled')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='core.optionaloffer')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='optional_charges', to='core.student')),
            ],
        ),
        migrations.CreateModel(
            name='OptionalChargePayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_date', models.DateTimeField(auto_now_add=True)),
                ('method', models.CharField(blank=True, max_length=50, null=True)),
                ('reference', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('mpesa_transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='optional_payments', to='core.mpesatransaction')),
                ('student_optional_charge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='core.studentoptionalcharge')),
            ],
            options={
                'ordering': ['-payment_date'],
            },
        ),
        migrations.AddIndex(
            model_name='optionaloffer',
            index=models.Index(fields=['term'], name='core_option_term_id_9fc107_idx'),
        ),
        migrations.AddIndex(
            model_name='studentoptionalcharge',
            index=models.Index(fields=['offer'], name='core_studen_offer_i_9c9287_idx'),
        ),
        migrations.AddIndex(
            model_name='studentoptionalcharge',
            index=models.Index(fields=['student'], name='core_studen_student_a2d421_idx'),
        ),
        migrations.AddIndex(
            model_name='studentoptionalcharge',
            index=models.Index(fields=['status'], name='core_studen_status_1527ce_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='studentoptionalcharge',
            unique_together={('offer', 'student')},
        ),
        migrations.AddIndex(
            model_name='optionalchargepayment',
            index=models.Index(fields=['payment_date'], name='core_option_payment_aa589b_idx'),
        ),
    ]
