# Generated by Django 5.2.4 on 2025-09-01 17:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0055_optionalchargecategory_alter_feepayment_student_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LessonPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_date', models.DateField(blank=True, null=True)),
                ('topic', models.CharField(blank=True, default='', max_length=255)),
                ('subtopic', models.CharField(blank=True, default='', max_length=255)),
                ('duration_minutes', models.PositiveIntegerField(blank=True, db_index=True, null=True)),
                ('duration_text', models.CharField(blank=True, default='', max_length=50)),
                ('objectives', models.TextField(blank=True, default='')),
                ('methods', models.TextField(blank=True, default='')),
                ('aids', models.TextField(blank=True, default='')),
                ('assessment', models.TextField(blank=True, default='')),
                ('opening_time', models.PositiveIntegerField(blank=True, null=True)),
                ('main_time', models.PositiveIntegerField(blank=True, null=True)),
                ('closing_time', models.PositiveIntegerField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('class_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_plans', to='core.class')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lesson_plans_deleted', to=settings.AUTH_USER_MODEL)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_plans', to='core.subject')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_plans', to='core.teacher')),
                ('term', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lesson_plans', to='core.term')),
            ],
            options={
                'indexes': [models.Index(fields=['teacher'], name='core_lesson_teacher_e7c728_idx'), models.Index(fields=['class_group'], name='core_lesson_class_g_7739c2_idx'), models.Index(fields=['subject'], name='core_lesson_subject_2af2ca_idx'), models.Index(fields=['plan_date'], name='core_lesson_plan_da_53ef0c_idx'), models.Index(fields=['term'], name='core_lesson_term_id_beb6d1_idx'), models.Index(fields=['is_deleted'], name='core_lesson_is_dele_496205_idx')],
            },
        ),
    ]
