# Generated by Django 5.2.4 on 2025-09-01 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0056_lessonplan'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessonplan',
            name='lesson_number',
            field=models.PositiveIntegerField(blank=True, db_index=True, null=True),
        ),
    ]
