# Generated by Django 5.2.4 on 2025-09-02 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0057_lessonplan_lesson_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='feecategory',
            name='is_optional',
            field=models.BooleanField(default=False, help_text='If checked, this category is optional and can be excluded from mandatory fee calculations.'),
        ),
    ]
