# Generated by Django 5.2.4 on 2025-09-02 06:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0058_feecategory_is_optional'),
    ]

    operations = [
        migrations.AddField(
            model_name='financemessagehistory',
            name='job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='finance_logs', to='core.notificationjob'),
        ),
        migrations.AddField(
            model_name='notificationjob',
            name='cancel_requested',
            field=models.BooleanField(default=False),
        ),
    ]
