# Generated by Django 5.2.3 on 2025-08-14 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_name', models.CharField(default='Greenwood High', max_length=255)),
                ('school_aim', models.TextField(blank=True, default='To nurture and inspire every student to reach their full potential.')),
                ('school_motto', models.CharField(blank=True, default='Excellence Through Diligence', max_length=255)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Site Settings',
                'verbose_name_plural': 'Site Settings',
            },
        ),
    ]
