# Generated by Django 5.2.3 on 2025-08-14 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0003_galleryimage_sitesettings_favicon_sitesettings_logo'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('slug', models.SlugField(max_length=160, unique=True)),
                ('content', models.TextField(blank=True, default='')),
                ('is_published', models.BooleanField(default=True)),
                ('show_in_nav', models.BooleanField(default=True)),
                ('menu_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Web Page',
                'verbose_name_plural': 'Web Pages',
                'ordering': ['menu_order', 'title'],
            },
        ),
    ]
