# Generated by Django 5.2.3 on 2025-08-14 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0005_category_delete_webpage'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
    ]
