# Generated by Django 5.2.3 on 2025-08-14 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0006_category_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='template',
            field=models.CharField(choices=[('card', 'Card Grid'), ('feature', 'Feature Block'), ('highlight', 'Highlight Banner')], default='card', max_length=20),
        ),
    ]
