# Generated by Django 5.2.3 on 2025-08-14 08:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0007_category_template'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='template',
            field=models.CharField(choices=[('card', 'Card Grid'), ('feature', 'Feature Block'), ('highlight', 'Highlight Banner'), ('single_photo', 'Single Photo'), ('gallery', 'Photo Gallery'), ('video', 'Video'), ('file', 'Download File'), ('all_media', 'All Media')], default='card', max_length=20),
        ),
        migrations.CreateModel(
            name='CategoryMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('image', 'Image'), ('video', 'Video'), ('file', 'File')], max_length=10)),
                ('image', models.ImageField(blank=True, null=True, upload_to='category_media/images/')),
                ('file', models.FileField(blank=True, null=True, upload_to='category_media/files/')),
                ('video_url', models.URLField(blank=True, default='', help_text='YouTube/Vimeo URL or direct video URL')),
                ('caption', models.CharField(blank=True, default='', max_length=255)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='landing.category')),
            ],
            options={
                'verbose_name': 'Category Media',
                'verbose_name_plural': 'Category Media',
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
