# Generated by Django 5.2.4 on 2025-08-14 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0008_alter_category_template_categorymedia'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='video_side_text',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='categorymedia',
            name='file',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to='category_media/files/'),
        ),
        migrations.AlterField(
            model_name='categorymedia',
            name='image',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='category_media/images/'),
        ),
    ]
