# Generated by Django 5.2.4 on 2025-08-14 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0009_category_video_side_text_alter_categorymedia_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='hero_video',
            field=models.FileField(blank=True, null=True, upload_to='branding/'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='hero_video_url',
            field=models.URLField(blank=True, default=''),
        ),
    ]
