# Generated by Django 5.0.7 on 2025-08-23 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0010_sitesettings_hero_video_sitesettings_hero_video_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='fee_restriction_message',
            field=models.CharField(blank=True, default='Results are temporarily unavailable due to outstanding fees. Please clear at least 50% to access.', help_text='Message shown to restricted students.', max_length=255),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='fee_restriction_threshold',
            field=models.PositiveIntegerField(default=50, help_text='Block results if balance percent is greater than this value (e.g., 50 = balance > 50%).'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='restrict_results_by_fee',
            field=models.BooleanField(default=False, help_text='If enabled, students with fee balances above the threshold cannot view or download results.'),
        ),
    ]
