# Generated by Django 5.2.4 on 2025-09-03 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0011_sitesettings_fee_restriction_message_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='announcement_cta_link',
            field=models.CharField(blank=True, default='/login/', max_length=255),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='announcement_cta_text',
            field=models.CharField(blank=True, default='View Details', max_length=100),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='announcement_text',
            field=models.CharField(blank=True, default='Admissions for the new term are open. Visit the office or login to the portal for details.', max_length=255),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='hero_stats_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='quicklink_admissions_url',
            field=models.URLField(blank=True, default='/login/'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='quicklink_downloads_url',
            field=models.URLField(blank=True, default='#'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='quicklink_term_dates_url',
            field=models.URLField(blank=True, default='#'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='stat_clubs',
            field=models.CharField(blank=True, default='25+', max_length=50),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='stat_passrate',
            field=models.CharField(blank=True, default='95%', max_length=50),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='stat_students',
            field=models.CharField(blank=True, default='1,200+', max_length=50),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='stat_teachers',
            field=models.CharField(blank=True, default='80+', max_length=50),
        ),
    ]
